"""role and aproved fields

Revision ID: a5951ea5b9b7
Revises: bd66c9bc66b6
Create Date: 2026-06-29 16:33:52.750225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5951ea5b9b7'
down_revision = 'bd66c9bc66b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False, server_default='USER'))
        batch_op.add_column(sa.Column('is_aproved', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_aproved')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
